#!/usr/bin/env python3
# This file is part of the Diffractor photo and video organizer
# Copyright 2026  Zac Walker
#
# Purpose: Compare the two FFmpeg configurations against each other. The fork is configured twice
# and nothing keeps the two answers in step: Windows compiles from a checked-in config-x64.h
# because configure needs a shell, while Linux runs the fork's own configure. A format can
# therefore be supported on one platform and silently absent on the other, and no build failure,
# test or diff reveals it.
#
# This has already found four divergences, each silent: zlib declined by --disable-autodetect and
# with it thirty-odd decoders, libopenmpt never asked for, network demuxers present on one side
# only, and the entire encoder and muxer set being compiled into a reader. See docs/linux.md.
#
# The divergences that remain are real and expected -- the hardware accelerators, Media Foundation
# and SChannel are Windows-only by nature -- so the guard is not "no divergence" but "no divergence
# that has not been accounted for". The accepted set is checked in beside the fork, and any change
# to it fails until someone looks and re-records it.
#
#   python tools/compare_ffmpeg_config.py            compare, and fail on an unaccounted difference
#   python tools/compare_ffmpeg_config.py --update   re-record the accepted set

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Both platforms split their switches across two generated headers, and the component list -- every
# decoder, demuxer, encoder and muxer, which is what this comparison is for -- is in the second.
# Windows checks in one per architecture plus a shared component list; Linux generates both into the
# build's staging directory, which also holds a copy of the Windows headers that must not be read.
WINDOWS_DIR = REPO_ROOT / "third-party" / "FFmpeg"
WINDOWS_HEADERS = ("config-x64.h", "config_components.h")

LINUX_DIR = REPO_ROOT / "tmp" / "linux-build" / "third-party" / "ffmpeg" / "src"
LINUX_HEADERS = ("config.h", "config_components.h")

BASELINE = REPO_ROOT / "third-party" / "ffmpeg-config-divergence.txt"

DEFINE = re.compile(r"^#define\s+(CONFIG_[A-Z0-9_]+)\s+(\S+)")


def enabled_switches(directory: Path, headers: tuple[str, ...]) -> set[str]:
    """The CONFIG_* switches this configuration turns on, across all of its headers."""
    enabled = set()

    for name in headers:
        path = directory / name

        if not path.exists():
            sys.exit(
                f"{path} does not exist.\n"
                "The Linux configuration is generated by the build, so build first:\n"
                "  ./dd build --config Release"
            )

        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            match = DEFINE.match(line)
            if match and match.group(2) != "0":
                enabled.add(match.group(1))

    if not enabled:
        sys.exit(f"{directory} defines no enabled CONFIG_ switches, which cannot be right.")

    return enabled


def divergence(windows: set[str], linux: set[str]) -> list[str]:
    """The accounted-set format: one side and one switch per line, ordered so it diffs cleanly."""
    return sorted(f"WINDOWS {name}" for name in windows - linux) + sorted(
        f"LINUX {name}" for name in linux - windows
    )


def read_baseline(path: Path) -> list[str]:
    lines = []

    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            lines.append(stripped)

    return lines


def write_baseline(path: Path, lines: list[str]) -> None:
    header = [
        "# FFmpeg configuration divergence, accepted.",
        "#",
        "# Generated by tools/compare_ffmpeg_config.py --update. Each line names the platform that",
        "# enables a switch the other does not. Read every line before re-recording: each should be",
        "# platform by nature -- the hardware accelerators, Media Foundation and SChannel on the",
        "# Windows side, glibc's iconv on the Linux side. A decoder, demuxer, encoder or muxer here is",
        "# a defect rather than a divergence, and so is anything that is merely a choice one side made.",
        "#",
        "# See docs/linux.md, 'FFmpeg is configured twice, and the two answers differ'.",
        "",
    ]
    path.write_text("\n".join(header + lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare the two FFmpeg configurations")
    parser.add_argument("--windows", type=Path, default=WINDOWS_DIR,
                        help="directory holding the checked-in Windows headers")
    parser.add_argument("--linux", type=Path, default=LINUX_DIR,
                        help="directory holding the headers the Linux build generated")
    parser.add_argument("--baseline", type=Path, default=BASELINE)
    parser.add_argument("--update", action="store_true", help="re-record the accepted set")
    args = parser.parse_args()

    current = divergence(
        enabled_switches(args.windows, WINDOWS_HEADERS),
        enabled_switches(args.linux, LINUX_HEADERS),
    )

    if args.update:
        write_baseline(args.baseline, current)
        print(f"Recorded {len(current)} accepted divergence(s) in {args.baseline}")
        return 0

    if not args.baseline.exists():
        print(f"{args.baseline} does not exist, so nothing is accounted for yet.")
        print("Review the divergence below, then record it with --update:")
        print()
        for line in current:
            print(f"  {line}")
        return 1

    accepted = read_baseline(args.baseline)
    appeared = [line for line in current if line not in accepted]
    resolved = [line for line in accepted if line not in current]

    if not appeared and not resolved:
        print(f"FFmpeg configurations agree, with {len(accepted)} accounted divergence(s).")
        return 0

    if appeared:
        print("New divergence. One platform enables these and the other does not:")
        print()
        for line in appeared:
            print(f"  + {line}")
        print()
        print("A decoder, demuxer or format here means the two configure lines have drifted.")

    if resolved:
        print("Accounted divergence that no longer exists, so the record is stale:")
        print()
        for line in resolved:
            print(f"  - {line}")

    print()
    print(f"Re-record with: python {Path(__file__).name} --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())
