// This file is part of the Diffractor photo and video organizer
// Copyright(C) 2022  Zac Walker
// 
// This program is free software; you can redistribute it and / or modify it
// under the terms of the LGPL License either version 2.1 or later.
// License details are available at https://www.gnu.org/licenses/lgpl-2.1.html
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY

#include "pch.h"
#include "app_text.h"

std::u8string language_name(const std::u8string_view code)
{
	static const df::hash_map<std::u8string_view, std::u8string_view> code_to_name = {
		{u8"en"sv, u8"English"sv},
		{u8"de"sv, u8"Deutsch (German)"sv},
		{u8"br"sv, u8"brezhoneg (Breton)"sv},
		{u8"cs"sv, u8"čeština (Czech)"sv},
		{u8"es"sv, u8"Español (Spanish)"sv},
		{u8"fr"sv, u8"Français (French)"sv},
		{u8"it"sv, u8"Italiano (Italian)"sv},
		{u8"ja"sv, u8"日本語 (Japanese)"sv},
		{u8"lv"sv, u8"Latviešu Valoda (Latvian)"sv},
		{u8"nl"sv, u8"Nederlands (Dutch)"sv},
		{u8"pl"sv, u8"Polszczyzna (Polish)"sv},
		{u8"pt"sv, u8"Português (Portuguese)"sv},
		{u8"ru"sv, u8"Русский (Russian)"sv},
		{u8"sr"sv, u8"српски језик (Serbian)"sv},
		{u8"zh"sv, u8"中文 (Chinese)"sv},
	};

	const auto found = code_to_name.find(code);
	return found == code_to_name.end() ? std::u8string(code) : std::u8string(found->second);
}

std::u8string un_quote_and_un_escape(const std::u8string& text)
{
	auto result = std::u8string(text);
	const auto n = result.find_first_not_of(u8" \t\r\n"sv);
	const std::u8string quoted(result, n);

	if (quoted.size() > 1 && quoted[0] == '"' && quoted[quoted.size() - 1] == '"')
	{
		result = std::u8string(quoted.begin() + 1, quoted.end() - 1);
	}
	else
	{
		result = quoted;
	}

	result = str::replace(result, u8"\\n"sv, u8"\n"sv);
	result = str::replace(result, u8"\\\""sv, u8"\""sv);
	result = str::replace(result, u8"\\\\"sv, u8"\\"sv);
	return result;
}

std::u8string_view tt_prep(std::u8string_view result)
{
	const auto comment = result.find(u8"//"sv);

	if (comment != std::u8string::npos)
	{
		result = result.substr(0, comment);
	}

	return result;
}

static void store_po_entry(lang_def& result, std::u8string& msgid, std::u8string& msgid_plural, std::u8string& msgstr,
                           std::u8string& msgstr1)
{
	if (!msgid.empty() && !msgstr.empty())
	{
		result[msgid] = msgstr;
		msgid.clear();
		msgstr.clear();
	}

	if (!msgid_plural.empty() && !msgstr1.empty())
	{
		result[msgid_plural] = msgstr1;
		msgstr1.clear();
		msgid_plural.clear();
	}
}

static lang_def load_po(const df::file_path lang_file)
{
	lang_def result;
	std::basic_ifstream<char8_t, std::char_traits<char8_t>> fs(platform::to_file_system_path(lang_file));
	//fs.imbue(std::locale("en_US.UTF-8"sv));

	struct po_mapping
	{
		std::u8string_view key;
		std::u8string& text;
	};

	std::u8string msgid;
	std::u8string msgstr1;
	std::u8string msgstr;
	std::u8string msgid_plural;
	int mapping_i = -1;

	po_mapping mapping[]
	{
		{u8"msgstr[1]"sv, msgstr1},
		{u8"msgstr[0]"sv, msgstr},
		{u8"msgid_plural"sv, msgid_plural},
		{u8"msgstr"sv, msgstr},
		{u8"msgid"sv, msgid},
	};

	while (fs)
	{
		std::u8string line;
		std::getline(fs, line);

		std::u8string::size_type pos = line.find_last_not_of(u8" \t\r\n"sv);
		if (pos != std::u8string::npos && pos < line.size() - 1)
		{
			line.erase(pos + 1, std::u8string::npos);
		}

		if (line.empty() || line[0] == '#' || line.empty())
		{
			store_po_entry(result, msgid, msgid_plural, msgstr, msgstr1);
		}
		else
		{
			try
			{
				bool key_line = false;

				for (int i = 0; i < 5; ++i)
				{
					const auto& m = mapping[i];

					if (str::starts(line, m.key))
					{
						line.erase(0, m.key.size() + 1);
						mapping[i].text = un_quote_and_un_escape(line);
						mapping_i = i;
						key_line = true;
						break;
					}
				}

				if (!key_line && mapping_i != -1)
				{
					mapping[mapping_i].text += un_quote_and_un_escape(line);
				}
			}
			catch (std::invalid_argument&)
			{
			}
		}
	}

	store_po_entry(result, msgid, msgid_plural, msgstr, msgstr1);

	return result;
}

void app_text_t::load_lang(const df::file_path lang_file)
{
	const std::vector<std::reference_wrapper<text_t>> texts
	{
		about_info,
		add_folder,
		adjust_date_help,
		after,
		album_artist,
		analyzing,
		archive,
		archives,
		ask_question,
		audio,
		audio_title,
		authorized,
		before,
		brightness,
		burn_title,
		button_analyze,
		button_background,
		button_cancel,
		button_change,
		button_close,
		button_convert,
		button_delete,
		button_dont_save,
		button_import,
		button_ok,
		button_rotate,
		button_save,
		button_save_as_jpeg,
		button_send,
		button_sync,
		button_tag,
		button_update,
		donate,
		donate_help,
		donate_link,
		cancel_was_pressed_after,
		cannot_edit,
		changes,
		click_collection_options,
		click_map_to_select,
		click_to_search_similar,
		click_to_search,
		click_to_open,
		collection_contains,
		collection_contains2,
		items_created_fmt,
		items_modified_fmt,
		click_to_open_created_modified,
		click_items_from_fmt,
		filter,
		close,
		collection_options,
		collection_options_custom_folders_help,
		collection_options_custom_folders_title,
		collection_options_custom_locations_help,
		collection_options_desktop,
		collection_options_documents,
		collection_options_downloads,
		collection_options_dropbox,
		collection_options_google_drive,
		collection_options_help,
		collection_options_info,
		collection_options_local_folders_title,
		collection_options_more_folders,
		collection_options_more_information,
		collection_options_music,
		collection_options_onedrive,
		collection_options_pictures,
		collection_options_videos,
		collection_title,
		color,
		command_adjust_date,
		command_advanced_search,
		command_album_artist,
		command_app_exit,
		command_browse_back,
		command_browse_forward,
		command_browse_next_folder,
		command_browse_next_group,
		command_browse_next_item,
		command_browse_next_item_extend,
		command_browse_parent,
		command_browse_previous_folder,
		command_browse_previous_group,
		command_browse_previous_item,
		command_browse_previous_item_extend,
		command_burn,
		command_capture,
		command_close,
		command_collection_options,
		command_color_reset,
		command_convert_or_resize,
		command_copy,
		command_copyright,
		command_crash,
		command_boom,
		command_customise,
		command_delete,
		command_desktop_background,
		command_display_options,
		command_download,
		command_edit,
		command_edit_copy,
		command_edit_cut,
		command_edit_metadata,
		command_edit_paste,
		command_eject,
		command_favorite,
		command_file_properties,
		command_file_search,
		command_flatten,
		command_fullscreen,
		command_group_album,
		command_group_camera,
		command_group_created,
		command_group_extension,
		command_group_file_type,
		command_group_location,
		command_group_modified,
		command_group_resolution,
		command_group_presence,
		command_group_rating,
		command_group_shuffle,
		command_group_size,
		command_group_folder,
		command_highlight_large_items,
		command_import,
		command_keyboard,
		command_label_approved,
		command_label_none,
		command_label_review,
		command_label_second,
		command_label_select,
		command_label_to_do,
		command_language,
		command_locate,
		command_maximize,
		command_menu_group_sort,
		command_minimize,
		command_move,
		command_nav_bar,
		command_navigate,
		command_new_folder,
		command_new_version,
		command_open,
		command_open_google_map,
		command_open_with,
		command_options,
		command_pin,
		command_play,
		command_print,
		command_rate,
		command_rate_0,
		command_rate_1,
		command_rate_2,
		command_rate_3,
		command_rate_4,
		command_rate_5,
		command_rate_rejected,
		command_refresh,
		command_related,
		command_rename,
		command_repeat_toggle,
		command_restore,
		command_revert,
		command_rotate_anticlockwise,
		command_rotate_clockwise,
		command_rotate_reset,
		command_run_tests,
		command_save,
		command_save_and_back,
		command_save_and_back_tooltip,
		command_save_and_next,
		command_save_and_next_tooltip,
		command_save_as,
		command_save_options,
		command_scale_up,
		command_scan,
		command_select_all,
		command_select_invert,
		command_select_nothing,
		command_share_email,
		command_show_in_file_browser,
		command_show_in_folder,
		command_show_thumbnails,
		command_sort_date_modified,
		command_sort_dates_ascending,
		command_sort_dates_descending,
		command_sort_def,
		command_sort_name,
		command_sort_size,
		command_sync,
		command_test_new_version,
		command_toggle_details,
		command_toggle_group_by,
		command_toggle_item_size,
		command_tools,
		command_view_help,
		command_view_items,
		command_view_large_font,
		command_view_menu,
		command_view_rate_label,
		command_view_select,
		command_view_sort,
		command_view_tests,
		command_toggle_volume,
		command_zoom,
		compare,
		compare_tooltip,
		contrast,
		copy_to_clipboard,
		copy_to_join,
		copyright_creator,
		copyright_credit,
		copyright_notice,
		copyright_source,
		copyright_title,
		copyright_url,
		count,
		customise_searches_title,
		customise_sidebar_title,
		customise_sidebar_desc,
		customise_tags_help,
		customise_tags_title,
		customize_display_title,
		customize_labels,
		customize_ratings,
		customize_show_drives,
		customize_show_history,
		customize_show_indexed_folders,
		customize_show_searches,
		customize_show_tags,
		customize_show_total,
		customize_show_world_map,
		darks,
		data,
		dates_file_created,
		dates_file_modified,
		dates_metadata_created,
		dates_title,
		default_favorite_tags,
		default_write_name,
		defragment_and_compact,
		defragmenting,
		delete_error,
		delete_fmt,
		desktop_background_info,
		dest_folder_label,
		dest_name_label,
		destination_folder,
		detecting_folders,
		disk_capacity,
		disk_free,
		disk_label,
		disk_system,
		disk_used,
		documentation,
		duplicates,
		duplicates_tooltip,
		editing_title,
		eject_close_info,
		eject_failed_fmt,
		eject_help,
		eject_title_fmt,
		email_connecting_to_mapi,
		email_convert_to_jpeg,
		email_failed,
		email_limit_dimensions,
		email_processing_fmt,
		email_sending,
		email_small_help,
		email_zip,
		empty,
		ending_fmt,
		error_access_denied_src,
		error_atl_failed,
		error_cannot_continue,
		error_connect_scanner,
		error_create_file_failed_fmt,
		error_create_folder_failed_fmt,
		error_create_window_failed,
		error_dest_is_cd_record,
		error_dest_is_cd_rom,
		error_dest_is_dvd,
		error_dest_same_tree,
		error_dest_subtree,
		error_diff_dir,
		error_dst_root_dir,
		error_file_dest_is_fld,
		error_file_too_large,
		error_filename_too_long,
		error_fld_dest_is_file,
		error_index_database_failed,
		error_internet,
		error_invalid_files,
		error_invalid_path_fmt,
		error_invalid_path,
		error_many_dest,
		error_many_src_1_dest,
		error_mapi_failed,
		error_max,
		error_ole_failed,
		error_on_dest,
		error_op_cancelled,
		error_path_too_deep,
		error_rename_failed,
		error_same_file,
		error_save_failed,
		error_save_image,
		error_scanner,
		error_src_is_cd_record,
		error_src_is_cdrom,
		error_src_is_dvd,
		error_src_root_dir,
		error_sse2_needed,
		error_unknown,
		error_unsupported_os,
		error_windows_common_controls_failed,
		error_winsock_failed,
		exif_metadata_title,
		failed_connect_internet,
		failed_to_create_folder_fmt,
		favorite_add_fmt,
		favorite_failed_to_add,
		favorite_remove_fmt,
		favorite_title,
		favorite_info,
		collection_add_fmt,
		collection_remove_fmt,
		collection_info,
		folder,
		folder_music,
		folder_noun,
		folder_noun_plural,
		folder_onedrive,
		folder_picture,
		folder_title,
		folder_video,
		folders,
		genre_a_capella,
		genre_abstract,
		genre_acid,
		genre_acidjazz,
		genre_acidpunk,
		genre_acoustic,
		genre_action,
		genre_action_adventure,
		genre_aerial,
		genre_alternative,
		genre_alternrock,
		genre_ambient,
		genre_analog,
		genre_animation,
		genre_anime,
		genre_architectural,
		genre_avantgarde,
		genre_aviation,
		genre_ballad,
		genre_bass,
		genre_bebob,
		genre_bigband,
		genre_bluegrass,
		genre_blues,
		genre_booty_bass,
		genre_brazilian,
		genre_cabaret,
		genre_candid,
		genre_celtic,
		genre_chambermusic,
		genre_chanson,
		genre_childrens,
		genre_chorus,
		genre_christian_gospel,
		genre_christianran_reap,
		genre_classic,
		genre_classic_rock,
		genre_classical,
		genre_close_up,
		genre_cloudscape,
		genre_club,
		genre_comedy,
		genre_conceptual,
		genre_concert,
		genre_concert_films,
		genre_conservation,
		genre_country,
		genre_cult,
		genre_dance,
		genre_dance_hall,
		genre_darkwave,
		genre_death_metal,
		genre_disco,
		genre_documentary,
		genre_drama,
		genre_dream,
		genre_drum_solo,
		genre_duet,
		genre_easylistening,
		genre_electronic,
		genre_ethnic,
		genre_euro_dance,
		genre_euro_house,
		genre_euro_techno,
		genre_family,
		genre_fashion,
		genre_fast_fusion,
		genre_film_still,
		genre_fine_art,
		genre_fire,
		genre_fireworks,
		genre_fitness_workout,
		genre_folk,
		genre_folk_rock,
		genre_folklore,
		genre_food,
		genre_foreign,
		genre_forensic,
		genre_freestyle,
		genre_funk,
		genre_fusion,
		genre_game,
		genre_gangsta,
		genre_geophotography,
		genre_glamour,
		genre_gospel,
		genre_gothic,
		genre_gothic_rock,
		genre_grunge,
		genre_hardrock,
		genre_high_speed,
		genre_highke,
		genre_hip_hop,
		genre_hip_hop_rap,
		genre_holiday,
		genre_horror,
		genre_house,
		genre_humour,
		genre_independent,
		genre_industrial,
		genre_instrumental,
		genre_instrumental_pop,
		genre_instrumental_rock,
		genre_jazz,
		genre_jazzfun,
		genre_jungle,
		genre_kids,
		genre_kids_family,
		genre_kirlian,
		genre_landscape,
		genre_latin,
		genre_lifestyle,
		genre_lo_fi,
		genre_lomography,
		genre_long_exposure,
		genre_low_key,
		genre_macro,
		genre_medical,
		genre_meditative,
		genre_metal,
		genre_monochrome,
		genre_music_documentaries,
		genre_music_feature_films,
		genre_musical,
		genre_musicals,
		genre_narrative,
		genre_nationa_folk,
		genre_native_american,
		genre_new_age,
		genre_new_wave,
		genre_night,
		genre_noise,
		genre_nonfiction,
		genre_oldies,
		genre_opera,
		genre_other,
		genre_panorama,
		genre_panoramic,
		genre_pellier_noir,
		genre_photo_op,
		genre_photobiography,
		genre_photojournalism,
		genre_photowalking,
		genre_podcast,
		genre_polaroid,
		genre_polka,
		genre_pop,
		genre_pop_folk,
		genre_pop_funk,
		genre_porn_groove,
		genre_portrait,
		genre_power_ballad,
		genre_pranks,
		genre_primus,
		genre_progressive_rock,
		genre_psychadelic,
		genre_psychedelic_rock,
		genre_punk,
		genre_punk_rock,
		genre_randb,
		genre_rap,
		genre_rave,
		genre_reality_tv,
		genre_reggae,
		genre_retro,
		genre_revival,
		genre_rhythmic_soul,
		genre_rock,
		genre_rock_and_roll,
		genre_romance,
		genre_samba,
		genre_satellite,
		genre_satire,
		genre_scifi_and_fantasy,
		genre_short_films,
		genre_show_tunes,
		genre_singer_songwriter,
		genre_ska,
		genre_slow_jam,
		genre_slow_rock,
		genre_social,
		genre_soft_focus,
		genre_sonata,
		genre_soul,
		genre_sound_clip,
		genre_soundtrack,
		genre_southern_rock,
		genre_space,
		genre_special_interest,
		genre_speech,
		genre_sports,
		genre_star_trail,
		genre_still_life,
		genre_stock,
		genre_street,
		genre_subminiature,
		genre_swing,
		genre_symphonic_rock,
		genre_symphony,
		genre_tango,
		genre_techno,
		genre_techno_industrial,
		genre_teens,
		genre_thriller,
		genre_time_lapse,
		genre_top40,
		genre_trailer,
		genre_trance,
		genre_travel,
		genre_tribal,
		genre_trip_hop,
		genre_ultraviolet,
		genre_underwater,
		genre_unknown,
		genre_urban,
		genre_vernacular,
		genre_vintage,
		genre_vocal,
		genre_war,
		genre_western,
		genre_world,
		group_sort_click,
		group_sort_tooltip,
		group_title_items,
		group_title_no_album_or_show,
		group_title_no_camera,
		group_title_no_extension,
		group_title_no_location,
		group_title_no_resolution,
		group_title_no_rating,
		group_title_no_value,
		group_title_shuffle,
		group_title_size_range_fmt,
		group_title_today,
		group_title_yesterday,
		has_changes,
		help_artist,
		help_more_info,
		help_send_info,
		help_tag_add_remove,
		help_tag1,
		help_tag2,
		hide_verbose_metadata,
		import_dest_folder,
		import_detecting,
		import_from,
		import_src_filter,
		import_ignore,
		import_ignore_previous,
		import_overwrite_if_newer,
		import_info,
		import_other_folder,
		import_overwrite,
		import_dest_folder_structure,
		import_rename_different_attributes,
		import_set_created_date,
		index_later,
		index_maintenance_help,
		index_maintenance_reset_recommended,
		index_maintenance_title,
		index_size_fmt,
		indexing,
		indexing_message,
		install_welcome_text1,
		install_welcome_text2,
		invalid,
		iptc_metadata_title,
		is_not_valid_folder_fmt,
		item_noun,
		item_noun_plural,
		item_oriented,
		item_oriented_tooltip_fmt,
		item_show_oriented,
		items_identical,
		items_not_identical,
		jpeg_best,
		keyboard,
		keyboard_accelerator_press,
		keyboard_alt,
		keyboard_back,
		keyboard_backspace,
		keyboard_basics_title,
		keyboard_browser_back,
		keyboard_browser_favorites,
		keyboard_browser_forward,
		keyboard_browser_home,
		keyboard_browser_refresh,
		keyboard_browser_search,
		keyboard_browser_stop,
		keyboard_control,
		keyboard_ctrl_left_right_desc,
		keyboard_del,
		keyboard_down,
		keyboard_enter,
		keyboard_enter_desc,
		keyboard_escape,
		keyboard_escape_desc,
		keyboard_f1,
		keyboard_f10,
		keyboard_f11,
		keyboard_f2,
		keyboard_f3,
		keyboard_f4,
		keyboard_f5,
		keyboard_f6,
		keyboard_f7,
		keyboard_f8,
		keyboard_f9,
		keyboard_file_management_title,
		keyboard_help_title,
		keyboard_insert,
		keyboard_left,
		keyboard_left_right_desc,
		keyboard_media_next_track,
		keyboard_media_play_pause,
		keyboard_media_prev_track,
		keyboard_media_stop,
		keyboard_navigation_title,
		keyboard_next,
		keyboard_oem_4,
		keyboard_oem_6,
		keyboard_oem_plus,
		keyboard_open_title,
		keyboard_options_title,
		keyboard_or,
		keyboard_playback_title,
		keyboard_prior,
		keyboard_rate_label_title,
		keyboard_ref_title,
		keyboard_right,
		keyboard_selection_title,
		keyboard_shift,
		keyboard_space,
		keyboard_space_desc,
		keyboard_tab,
		keyboard_tools_title,
		keyboard_up,
		keyboard_volume_down,
		keyboard_volume_mute,
		keyboard_volume_up,
		km_from,
		learn_more_diffractor_com,
		lights,
		limit_output_dimensions,
		lossless_compression,
		list_of_accelerators,
		listed,
		listed_sub_folders,
		loading,
		location_not_loaded,
		location_not_selected,
		location_overwrite_gps,
		location_title,
		maximize_image,
		maybe_later,
		media_metadata_title,
		menu_add_fmt,
		menu_copy,
		menu_cut,
		menu_delete,
		menu_move,
		menu_paste,
		menu_select_all,
		menu_undo,
		metadata,
		midtones,
		month_april,
		month_august,
		month_december,
		month_february,
		month_january,
		month_july,
		month_june,
		month_march,
		month_may,
		month_november,
		month_october,
		month_september,
		month_short_apr,
		month_short_aug,
		month_short_dec,
		month_short_feb,
		month_short_jan,
		month_short_jul,
		month_short_jun,
		month_short_mar,
		month_short_may,
		month_short_nov,
		month_short_oct,
		month_short_sep,
		move_items,
		nav_countries_title,
		nav_drives_title,
		nav_folders_title,
		nav_history_title,
		nav_search_title,
		nav_tags_title,
		need_some_maintenance,
		new_folder_name,
		new_folder_title,
		no_items_are_selected,
		no_results,
		none,
		not_supported_cloud,
		not_supported_folder,
		not_supported_photo,
		not_supported_readonly,
		not_supported_readonly_metadata,
		not_supported_save_format,
		nothing_found1,
		nothing_found2,
		num_of,
		ok_all_done,
		ok_got_it,
		open_dest,
		open_in_browser_title,
		open_properties_title,
		open_title,
		open_with_app,
		open_with_app_tool,
		open_with_failed,
		open_with_fmt,
		open_with_title,
		open_with_tool,
		optimize,
		option_overwrite_gps,
		option_slideshow_delay,
		options_advanced,
		options_app_options,
		options_auto_update,
		options_backup_copy,
		options_beta_tester,
		options_check_for_update,
		options_confirm_del,
		options_jpeg_quality,
		options_webp_quality,
		options_save_options,
		options_send_crash_reports,
		options_show_debug_info,
		options_show_hidden,
		options_show_rotated,
		options_updates,
		options_use_gpu,
		options_use_gpu_video,
		options_use_yuv_tex,
		options_show_shadow,
		options_update_modified,
		options_last_played_pos,
		options_show_help_tooltips,
		orientation_bottom_left,
		orientation_bottom_right,
		orientation_left_bottom,
		orientation_left_top,
		orientation_right_bottom,
		orientation_right_top,
		orientation_top_left,
		orientation_top_right,
		other,
		others,
		pasted_file_name,
		photo,
		photos,
		pixels_icon,
		pixels_identical_files_not_identical,
		resolution_none,
		pixels_small,
		pixels_title,
		png_best,
		presence_loading,
		presence_newer_in,
		presence_newer_in_long,
		presence_not_in,
		presence_not_in_long,
		presence_older_in,
		presence_older_in_long,
		presence_similar_in,
		presence_similar_in_long,
		presence_this_in,
		presence_this_in_long,
		presence_tile,
		preview_rendered,
		preview_rendering,
		preview_show_preview,
		preview_showing,
		print_title,
		processing,
		prop_name_35mmequivalent,
		prop_name_album,
		prop_name_albumartist,
		prop_name_artist,
		prop_name_audiocodec,
		prop_name_bitrate,
		prop_name_camera,
		prop_name_cameramanufacturer,
		prop_name_channels,
		prop_name_comment,
		prop_name_composer,
		prop_name_copyrightcreator,
		prop_name_copyrightcredit,
		prop_name_copyrightnotice,
		prop_name_copyrightsource,
		prop_name_copyrighturl,
		prop_name_country,
		prop_name_created,
		prop_name_createdexif,
		prop_name_description,
		prop_name_digitized,
		prop_name_dimensions,
		prop_name_disk,
		prop_name_doc_id,
		prop_name_duration,
		prop_name_encoder,
		prop_name_encodingtool,
		prop_name_episode,
		prop_name_exposure,
		prop_name_filename,
		prop_name_fnumber,
		prop_name_focallength,
		prop_name_game,
		prop_name_genre,
		prop_name_id,
		prop_name_iso,
		prop_name_label,
		prop_name_latitude,
		prop_name_lens,
		prop_name_longitude,
		prop_name_mediacategory,
		prop_name_megapixels,
		prop_name_modified,
		prop_name_null,
		prop_name_orientation,
		prop_name_performer,
		prop_name_pixelformat,
		prop_name_place,
		prop_name_publisher,
		prop_name_rating,
		prop_name_rawfile,
		prop_name_samplerate,
		prop_name_sampletype,
		prop_name_season,
		prop_name_show,
		prop_name_size,
		prop_name_state,
		prop_name_streams,
		prop_name_synopsis,
		prop_name_system,
		prop_name_tag,
		prop_name_title,
		prop_name_track,
		prop_name_videocodec,
		prop_name_year,
		query_age,
		query_and,
		query_created,
		query_duplicates,
		query_duplicates_alt1,
		query_duplicates_alt2,
		query_modified,
		query_or,
		query_related,
		query_with,
		query_without,
		rate_title,
		rating_keys,
		rating_remove_fmt,
		raw_metadata_title,
		remove_metadata_title,
		rename_label,
		rename_template_help,
		rename_template_label,
		rename_template_start_label,
		repeat_help,
		repeat_off_help,
		repeat_one_help,
		reset,
		reset_database,
		resetting,
		resized_max_label,
		retro,
		retro_title,
		saturation,
		save_as_jpeg_fmt,
		save_changes,
		save_new_photo,
		saving_file_name,
		scan_failed,
		search_all_terms,
		search_any_terms,
		search_audio,
		search_christmas,
		search_collection,
		search_date_from,
		search_date_until,
		search_folder,
		search_last_7_days,
		search_located_within,
		search_none_terms,
		search_not_in_collection,
		search_or_folder,
		search_photos,
		search_select_term,
		search_sub_folders,
		search_top_rated,
		search_videos,
		searching_text,
		select_folder,
		select_location,
		selected_date_range_label,
		selected_items_fmt,
		show_raw,
		show_raw_now,
		show_related,
		show_verbose_metadata,
		size_title,
		sort_by_album_show,
		sort_by_def,
		sort_by_extension,
		sort_by_file_type,
		sort_by_location,
		sort_by_name,
		sort_by_Folder,
		sort_by_resolution,
		sort_by_presence,
		sort_by_rating_label,
		sort_by_shuffle,
		sort_by_size,
		space_used,
		staring,
		starting_date_label,
		starting_fmt,
		straighten,
		stream_name_fmt,
		stream_select_fmt,
		subtitle,
		support,
		sync_collection,
		sync_copy_local_col,
		sync_copy_remote_col,
		sync_delete_local_col,
		sync_delete_remote_col,
		sync_details,
		sync_delete_local,
		sync_delete_remote,
		sync_local,
		sync_local_remote,
		sync_other_folder,
		sync_remote,
		sync_remote_folder,
		sync_remote_local,
		tag_add_or_remove_label,
		tag_add_remove,
		tag_selected,
		tags_common_label,
		tags_favorite_label,
		tags_remove_label,
		tags_title,
		text_false,
		text_true,
		title_error,
		title_folder,
		title_rate,
		title_updating,
		tooltip_color_reset,
		tooltip_edit1,
		tooltip_edit2,
		tooltip_flag_for_delete,
		tooltip_fullscreen,
		tooltip_language,
		tooltip_nav_bar,
		tooltip_open,
		tooltip_pin,
		tooltip_play,
		tooltip_revert,
		tooltip_rotate_reset,
		tooltip_scale_up,
		tooltip_tag_with,
		tooltip_toggle_details_selected,
		tooltip_toggle_details_all,
		tooltip_tools,
		tooltip_view_menu,
		tooltip_view_tests,
		total_title,
		truncated_at_one_mb,
		type_to_search,
		unknown,
		unselect_fmt,
		update,
		update_avail_version_fmt,
		update_available,
		update_current_version_fmt,
		update_failed,
		update_help,
		update_help_fmt,
		update_more_info,
		update_more_info_help,
		update_not_now,
		update_not_now_help,
		update_please_wait,
		update_title,
		version,
		vibrance,
		video,
		videos,
		webp_best,
		xmp_metadata_title,
		icc_metadata_title,
		zoom_kb,
		zoom_tooltip,
		scope,
		value,
		command_volume100,
		command_volume75,
		command_volume50,
		command_volume25,
		command_volume0,
		command_autoplay,
		command_last_played_pos,
		command_repeat_toggle,
		command_repeat_one,
		command_repeat_all,
		command_repeat_none,
		command_playback_menu,
		command_playback_toolbar,
		command_filter_photos,
		command_filter_videos,
		command_filter_audio,
		all_items_filtered,
		items_created_on_fmt,
		command_all_tags,
		command_favorite_tags,
		option_favorite_tags,
		collection_add,
	};

	const std::vector<std::reference_wrapper<plural_text>> plurals
	{
		rotate_info_fmt,
		title_folder_count_fmt,
		title_item_count_fmt,
		rating_set_fmt,
		cannot_process_fmt,
		rename_fmt,
		dup_count_fmt,
		sidecar_count_fmt,
		processed_x_of_x_fmt,
		processed_fmt,
		failed_items_fmt,
		ignored_fmt,
		ignored_exist_already_fmt,
		ignored_previous_fmt,
		delete_info_fmt,
		copy_fmt,
		move_fmt,
		be_updated_fmt,
		edit_metadata_fmt,
		convert_info_fmt,
		tag_info_fmt,
		adjust_date_info_fmt,
		shared_fmt,
		import_copy_fmt,
		email_info_fmt,
		would_overwrite_fmt,
		gps_overwrite_count_fmt,
	};

	// default
	*this = app_text_t();

	if (!lang_file.is_empty())
	{
		translations = load_po(lang_file);

		for (auto&& e : texts)
		{
			const auto found = translations.find(std::u8string(e));

			if (found != translations.end())
			{
				const auto found_value = found->second;
				e.get() = str::cache(found_value);
			}
			else
			{
				df::log(__FUNCTION__, str::format(u8"Missing language text {} - {}"sv, lang_file, e.get()));
			}
		}

		for (const auto& p : plurals)
		{
			const auto found_one = translations.find(std::u8string(p.get().one));

			if (found_one != translations.end())
			{
				const auto found_val = found_one->second;
				p.get().one = str::cache(found_val);
			}
			else
			{
				df::log(__FUNCTION__, str::format(u8"Missing language text {} - {}"sv, lang_file, p.get().one));
			}

			const auto found_plural = translations.find(std::u8string(p.get().plural));

			if (found_plural != translations.end())
			{
				auto found_val = found_plural->second;
				p.get().plural = str::cache(found_val);
			}
			else
			{
				df::log(__FUNCTION__, str::format(u8"Missing language text {} - {}"sv, lang_file, p.get().plural));
			}
		}
	}
}

std::u8string app_text_t::translate_text(const std::u8string& text, const std::u8string_view scope) const
{
	if (!scope.empty())
	{
		const auto found = translations.find(str::format(u8"{}//{}"sv, text, scope));

		if (found != translations.end())
		{
			return std::u8string(tt_prep(found->second));
		}
	}

	const auto found = translations.find(text);
	return found != translations.end() ? std::u8string(tt_prep(found->second)) : std::u8string(tt_prep(text));
}

std::vector<std::u8string> app_text_t::add_translate_text(const std::vector<str::cached>& text,
                                                          const std::u8string_view scope) const
{
	df::hash_set<std::u8string, df::ihash, df::ieq> result;
	result.reserve(text.size() * 2);

	for (const auto& t : text)
	{
		result.emplace(t.sv());
		result.emplace(translate_text(t.str(), scope));
	}

	return {result.begin(), result.end()};
}


app_text_t tt;

