// This file is part of the Diffractor photo and video organizer
// Copyright 2026  Zac Walker
// 
// This program is free software; you can redistribute it and / or modify it
// under the terms of the LGPL License either version 2.1 or later.
// License details are available at https://www.gnu.org/licenses/lgpl-2.1.html
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY

// Purpose: Generates the project wiki documentation pages ("Formats and Codecs"
// and "Metadata") from authoritative data in the codebase. Invoked from the
// command line via /gen-docs[:folder].

#include "pch.h"
#include "files.h"
#include "platform.h"
#include "av_format.h"
#include "metadata_xmp.h"

#include <cstdio>

namespace
{
	// Splits a comma separated extension list (e.g. "aif, aifc, aiff") into an
	// uppercased, normalised, comma separated string (e.g. "AIF, AIFC, AIFF").
	std::string format_extensions(const std::string_view extensions)
	{
		std::string result;

		for (const auto part : str::split(extensions, false, [](const wchar_t c) { return c == ','; }))
		{
			const auto trimmed = str::trim(part);
			if (trimmed.empty()) continue;

			if (!result.empty()) result += ", ";
			result += str::to_upper(trimmed);
		}

		return result;
	}

	// Markers that delimit the generated region within a wiki page. Text outside
	// these markers is hand-written narrative and is preserved across regenerations.
	constexpr std::string_view k_begin = "<!-- gen-docs:begin -->";
	constexpr std::string_view k_end = "<!-- gen-docs:end -->";

	// Note placed at the top of each generated block.
	constexpr std::string_view k_generated_note =
		"<!-- The tables in this section are generated by Diffractor "
		"(diffractor64.exe /gen-docs). Content between the gen-docs:begin and "
		"gen-docs:end markers is overwritten on each run; edit the surrounding "
		"text freely. -->\n\n";

	std::string read_text_file(const df::file_path path)
	{
		if (!platform::exists(path)) return {};
		const auto b = df::blob_from_file(path);
		return std::string(reinterpret_cast<const char*>(b.data()), b.size());
	}

	// Writes content to a wiki page, preserving any narrative outside the
	// gen-docs markers. If the existing page has both markers, only the region
	// between them is replaced with `block`. Otherwise the full `default_page`
	// (narrative shell + markers + block) is written.
	bool splice_and_save(const df::folder_path folder, const std::string_view file_name,
		const std::string& default_page, const std::string& block)
	{
		const auto path = folder.combine_file(file_name);
		const auto existing = read_text_file(path);

		std::string out;
		const auto b = existing.find(k_begin);
		const auto e = existing.find(k_end);

		if (b != std::string::npos && e != std::string::npos && e > b)
		{
			out.append(existing, 0, b + k_begin.size());
			out += "\n";
			out += block;
			out.append(existing, e, existing.size() - e);
			printf("  spliced %s (preserved surrounding text)\n", std::string(path.str()).c_str());
		}
		else
		{
			out = default_page;
			printf("  wrote %s (new page with markers)\n", std::string(path.str()).c_str());
		}

		const auto saved = df::blob_save_to_file(
			df::cspan(reinterpret_cast<const uint8_t*>(out.data()), out.size()), path);

		if (!saved)
		{
			printf("  ERROR: failed to write %s\n", std::string(path.str()).c_str());
		}

		return saved;
	}

	// Emits a markdown table of file types belonging to the given group, with an
	// optional raw-trait filter, including only types with a description.
	void write_format_table(std::string& md, const std::string_view section_title,
		const std::vector<file_type_ref>& types, const file_group_ref group,
		const bool require_raw, const bool exclude_raw)
	{
		md += "## ";
		md += section_title;
		md += "\n\n";
		md += "| Extensions | Description |\n";
		md += "| --- | --- |\n";

		for (const auto* ft : types)
		{
			if (ft->group != group) continue;
			if (ft->text.empty()) continue;

			const bool is_raw = ft->has_trait(file_traits::raw);
			if (require_raw && !is_raw) continue;
			if (exclude_raw && is_raw) continue;

			md += "| ";
			md += format_extensions(ft->extension);
			md += " | ";
			md += ft->text;
			md += " |\n";
		}

		md += "\n";
	}

	void write_codec_list(std::string& md, const std::string_view section_title,
		const std::vector<av_codec_doc>& codecs, const av_codec_media_type media_type)
	{
		md += "## ";
		md += section_title;
		md += "\n\n";

		bool first = true;

		for (const auto& c : codecs)
		{
			if (c.media_type != media_type) continue;
			if (c.name.empty()) continue;

			if (!first) md += ", ";
			md += c.name;
			first = false;
		}

		md += "\n\n";
	}

	bool generate_formats_page(const df::folder_path folder)
	{
		const auto types = all_file_types();
		const auto codecs = av_supported_codecs();

		std::string block;
		block += k_generated_note;
		write_format_table(block, "Image Formats", types, &file_group::photo, false, true);
		write_format_table(block, "Raw Photo Formats", types, &file_group::photo, true, false);
		write_format_table(block, "Video and Container Formats", types, &file_group::video, false, false);
		write_format_table(block, "Audio Formats", types, &file_group::audio, false, false);
		write_codec_list(block, "Video Codecs", codecs, av_codec_media_type::video);
		write_codec_list(block, "Audio Codecs", codecs, av_codec_media_type::audio);

		std::string default_page;
		default_page += "File formats and codecs supported by Diffractor are listed below.\n\n";
		default_page += k_begin;
		default_page += "\n";
		default_page += block;
		default_page += k_end;
		default_page += "\n";

		return splice_and_save(folder, "Formats-and-Codecs.md", default_page, block);
	}

	struct metadata_row
	{
		std::string_view property;
		std::string_view xmp;
		std::string_view exif;
		std::string_view iptc;
		std::string_view mp4_atom;
		std::string_view id3;
		std::string_view riff_other;
	};

	// Consolidated metadata mapping table. This is the single source of truth in
	// code for how Diffractor properties map onto the various metadata standards.
	const metadata_row s_metadata_rows[] = {
		{"album", "xmpDM:album", "", "", "©alb", "TALB", ""},
		{"album.artist", "xmpDM:albumArtist", "", "", "aART", "TPE2", ""},
		{"aperture", "", "APERTURE_VALUE", "", "", "", ""},
		{"artist", "xmpDM:artist dc:creator", "", "BYLINE", "©ART", "TPE1", "IART"},
		{"camera.manufacturer", "tiff:Make", "MAKE", "", "", "", ""},
		{"camera.model", "tiff:Model xmpDM:cameraModel", "MODEL", "", "", "", ""},
		{"city", "photoshop:City", "", "CITY", "", "", ""},
		{"comment", "exif:UserComment xmpDM:logComment", "USER_COMMENT USER_COMMENT_XP", "", "©cmt", "", "ICMT"},
		{"composer", "", "", "", "©wrt", "", ""},
		{"copyright", "dc:rights", "COPYRIGHT", "COPYRIGHT_NOTICE", "cprt", "", "ICOP"},
		{"country", "photoshop:Country", "", "COUNTRY_NAME", "", "", ""},
		{"created", "", "DATE_TIME DATE_TIME_DIGITIZED", "DATE_TIME_ORIGINAL", "", "", ""},
		{"credit", "photoshop:Credit", "", "CREDIT", "", "", ""},
		{"description", "dc:description", "IMAGE_DESCRIPTION", "CAPTION", "desc", "", ""},
		{"disk", "xmpDM:discNumber", "", "", "disk", "TPOS", ""},
		{"duration", "", "", "", "", "TLEN", ""},
		{"encoder", "", "", "", "©enc", "", ""},
		{"encoding.tool", "", "", "", "©too", "", ""},
		{"episode", "xmpDM:episode", "", "", "tves", "", ""},
		{"exposure", "", "EXPOSURE_TIME", "", "", "", ""},
		{"fnumber", "", "FNUMBER", "", "", "", ""},
		{"focal.length", "", "FOCAL_LENGTH", "", "", "", ""},
		{"genre", "xmpDM:genre", "", "", "gnre ©gen", "TCON", ""},
		{"iso", "", "ISO_SPEED_RATINGS", "", "", "", ""},
		{"latitude", "exif:GPSLatitude", "", "", "", "", ""},
		{"lens", "aux:Lens", "LENS_MODEL MNOTE_CANON_TAG_LENS", "", "", "", ""},
		{"longitude", "exif:GPSLongitude", "", "", "©xyz", "", ""},
		{"media.category", "", "", "", "stik", "", ""},
		{"orientation", "", "ORIENTATION", "", "", "", ""},
		{"rating", "xmp:Rating", "IMAGE_RATING IMAGE_RATING_PERCENT", "", "rate", "POPM", ""},
		{"season", "xmpDM:season", "", "", "tvsn", "", ""},
		{"show", "xmpDM:show", "", "", "tvsh", "", ""},
		{"source", "photoshop:Source", "", "SOURCE", "", "", ""},
		{"state", "photoshop:State", "", "STATE", "", "", ""},
		{"synopsis", "", "", "", "ldes", "", ""},
		{"tag", "dc:subject", "", "KEYWORDS", "keyw", "", ""},
		{"title", "dc:title", "", "OBJECT_NAME", "©nam", "TIT2", "INAM"},
		{"track", "xmpDM:trackNumber", "", "", "trkn", "TRCK", ""},
		{"year", "xmp:CreateDate", "", "", "©day", "TYER TDRC", ""},
	};

	bool generate_metadata_page(const df::folder_path folder)
	{
		std::string block;
		block += k_generated_note;
		block += "| Property | XMP | EXIF | IPTC | MP4 atom | ID3 | RIFF / Other |\n";
		block += "| --- | --- | --- | --- | --- | --- | --- |\n";

		const auto cell = [](const std::string_view s) -> std::string
		{
			return s.empty() ? std::string() : std::string(s);
		};

		for (const auto& row : s_metadata_rows)
		{
			block += "| ";
			block += cell(row.property);
			block += " | ";
			block += cell(row.xmp);
			block += " | ";
			block += cell(row.exif);
			block += " | ";
			block += cell(row.iptc);
			block += " | ";
			block += cell(row.mp4_atom);
			block += " | ";
			block += cell(row.id3);
			block += " | ";
			block += cell(row.riff_other);
			block += " |\n";
		}

		block += "\n";

		std::string default_page;
		default_page += "Metadata is information related to a media file. It may be embedded into the file or contained in a separate associated file.\n\n";
		default_page += "Diffractor can add or update metadata such as tags, rating, description, or location. It can also understand metadata added by a camera. Diffractor has a database to cache these values for faster searching. However, the values are primarily stored in metadata to allow compatibility with other programs.\n\n";
		default_page += "### Where is metadata stored?\n\n";
		default_page += "Jpeg, Tiff, Png, and Gif files have internal EXIF, IPTC, and XMP metadata extensions. Raw photos have a separate XMP file similar to Adobe products. MOV, MP4, and MP3 files have standard tags and also include an XMP block. MKV files contain an XMP block, this is not very standard and we plan to support Matroska tags in a future version. AVI files contain an XMP block.\n\n";
		default_page += "For advanced users, the table below describes the specific metadata fields read or updated by Diffractor:\n\n";
		default_page += k_begin;
		default_page += "\n";
		default_page += block;
		default_page += k_end;
		default_page += "\n";

		return splice_and_save(folder, "Metadata.md", default_page, block);
	}
}

int generate_wiki_docs(const std::string_view output_folder)
{
	load_file_types();
	metadata_xmp::initialise();

	df::folder_path folder = output_folder.empty()
		? platform::known_path(platform::known_folder::running_app_folder)
		: df::folder_path(output_folder);

	if (!platform::exists(folder))
	{
		platform::create_folder(folder);
	}

	if (!platform::exists(folder))
	{
		printf("ERROR: output folder does not exist: %s\n", std::string(folder.text().sv()).c_str());
		return 1;
	}

	printf("Generating wiki documentation in %s\n", std::string(folder.text().sv()).c_str());

	const bool ok_formats = generate_formats_page(folder);
	const bool ok_metadata = generate_metadata_page(folder);

	if (ok_formats && ok_metadata)
	{
		printf("Done.\n");
		return 0;
	}

	printf("Completed with errors.\n");
	return 1;
}
