// This file is part of the Diffractor photo and video organizer
// Copyright 2026  Zac Walker
// 
// This program is free software; you can redistribute it and / or modify it
// under the terms of the LGPL License either version 2.1 or later.
// License details are available at https://www.gnu.org/licenses/lgpl-2.1.html
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY

// Purpose: Icon definitions. Maps icon_index enum values to code points in the bundled
// Fluent UI System Icons font, which is embedded as IDF_ICONS and is the same on every platform.

#pragma once


// GENERATED by tools/fluent_icons.py from the font's own mapping file. The names in that script
// are what gets reviewed; these code points are assigned sequentially by the font build and move
// between releases, so never edit one by hand - re-run the generator instead.
enum class icon_index
{
	none = 0,
	add = 0xE00D, // ic_fluent_add_20_regular
	remove = 0xF1A3, // ic_fluent_subtract_20_regular
	add2 = 0xE00F, // ic_fluent_add_circle_20_regular
	remove2 = 0xF1A5, // ic_fluent_subtract_circle_20_regular
	audio = 0xF0E9, // ic_fluent_sound_wave_circle_20_regular
	music_note = 0xEC90, // ic_fluent_music_note_2_20_regular
	usb = 0xF4C7, // ic_fluent_usb_stick_20_regular
	hard_drive = 0xE9EF, // ic_fluent_hard_drive_20_regular
	back = 0xE115, // ic_fluent_arrow_left_20_regular
	back_image = 0xEA58, // ic_fluent_image_arrow_back_20_regular
	back_folder = 0xE8EF, // ic_fluent_folder_arrow_left_20_regular
	album_artist = 0xED75, // ic_fluent_people_20_regular
	tools = 0xF5FF, // ic_fluent_wrench_screwdriver_20_regular
	camera = 0xE3C2, // ic_fluent_camera_20_regular
	cancel = 0xE6D3, // ic_fluent_dismiss_20_regular
	check = 0xE460, // ic_fluent_checkmark_20_regular
	preview = 0xE883, // ic_fluent_eye_20_regular
	color = 0xE566, // ic_fluent_color_20_regular
	convert = 0xE16F, // ic_fluent_arrow_swap_20_regular
	swap = 0xE16F, // ic_fluent_arrow_swap_20_regular
	crop = 0xE5E9, // ic_fluent_crop_20_regular
	del = 0xE66D, // ic_fluent_delete_20_regular
	sdcard = 0xF091, // ic_fluent_sim_20_regular
	disk = 0xF18B, // ic_fluent_storage_20_regular
	document = 0xE6E9, // ic_fluent_document_20_regular
	edit = 0xE837, // ic_fluent_edit_20_regular
	eject = 0xE0E1, // ic_fluent_arrow_eject_20_regular
	flag = 0xE8B7, // ic_fluent_flag_20_regular
	folder = 0xE8EB, // ic_fluent_folder_20_regular
	fullscreen = 0xE951, // ic_fluent_full_screen_maximize_20_regular
	fullscreen_exit = 0xE953, // ic_fluent_full_screen_minimize_20_regular
	import = 0xE111, // ic_fluent_arrow_import_20_regular
	items = 0xE9C1, // ic_fluent_grid_20_regular
	details = 0xE07F, // ic_fluent_apps_list_detail_20_regular
	link = 0xEB68, // ic_fluent_link_20_regular
	location = 0xEB8C, // ic_fluent_location_20_regular
	map_pin = 0xEC1A, // ic_fluent_map_pin_20_regular
	world = 0xE99B, // ic_fluent_globe_20_regular
	mail = 0xEBBC, // ic_fluent_mail_20_regular
	navigation = 0xEB58, // ic_fluent_line_horizontal_3_20_regular
	next = 0xE141, // ic_fluent_arrow_right_20_regular
	next_image = 0xEA5C, // ic_fluent_image_arrow_forward_20_regular
	next_folder = 0xE8F1, // ic_fluent_folder_arrow_right_20_regular
	network = 0xF005, // ic_fluent_server_20_regular
	open_items = 0xECF6, // ic_fluent_open_folder_20_regular
	open_one = 0xECF4, // ic_fluent_open_20_regular
	more = 0xEC72, // ic_fluent_more_horizontal_20_regular
	new_folder = 0xE8ED, // ic_fluent_folder_add_20_regular
	settings = 0xF00F, // ic_fluent_settings_20_regular
	parent = 0xE8F3, // ic_fluent_folder_arrow_up_20_regular
	pause = 0xED5B, // ic_fluent_pause_20_regular
	photo = 0xEA52, // ic_fluent_image_20_regular
	play = 0xEE8D, // ic_fluent_play_20_regular
	print = 0xEEDB, // ic_fluent_print_20_regular
	repeat_all = 0xE135, // ic_fluent_arrow_repeat_all_20_regular
	repeat_one = 0xE133, // ic_fluent_arrow_repeat_1_20_regular
	repeat_none = 0xE137, // ic_fluent_arrow_repeat_all_off_20_regular
	refresh = 0xE0BF, // ic_fluent_arrow_clockwise_20_regular
	rotate_clockwise = 0xE143, // ic_fluent_arrow_rotate_clockwise_20_regular
	rotate_anticlockwise = 0xE145, // ic_fluent_arrow_rotate_counterclockwise_20_regular
	save = 0xEF99, // ic_fluent_save_20_regular
	save_copy = 0xEF9D, // ic_fluent_save_copy_20_regular
	scan = 0xEFB1, // ic_fluent_scan_20_regular
	fit = 0xE0F7, // ic_fluent_arrow_fit_20_regular
	search = 0xEFD7, // ic_fluent_search_20_regular
	shuffle = 0xE14B, // ic_fluent_arrow_shuffle_20_regular
	slideshow = 0xF0BD, // ic_fluent_slide_play_20_regular
	sort = 0xE14F, // ic_fluent_arrow_sort_20_regular
	group = 0xE9C7, // ic_fluent_group_20_regular
	recursive = 0xE0ED, // ic_fluent_arrow_expand_all_20_regular
	mute = 0xF113, // ic_fluent_speaker_mute_20_regular
	volume0 = 0xF105, // ic_fluent_speaker_0_20_regular
	volume1 = 0xF107, // ic_fluent_speaker_1_20_regular
	volume2 = 0xF109, // ic_fluent_speaker_2_20_regular
	volume3 = 0xF109, // ic_fluent_speaker_2_20_regular
	repair = 0xF5FD, // ic_fluent_wrench_20_regular
	star = 0xF15D, // ic_fluent_star_20_regular
	star_solid = 0xF15C, // ic_fluent_star_20_filled
	stop = 0xF189, // ic_fluent_stop_20_regular
	tag = 0xF283, // ic_fluent_tag_20_regular
	rename = 0xEF5D, // ic_fluent_rename_20_regular
	time = 0xE508, // ic_fluent_clock_20_regular
	video = 0xF4FB, // ic_fluent_video_20_regular
	movies = 0xEC7C, // ic_fluent_movies_and_tv_20_regular
	zoom_in = 0xF60F, // ic_fluent_zoom_in_20_regular
	zoom_out = 0xF611, // ic_fluent_zoom_out_20_regular
	wallpaper = 0xF55D, // ic_fluent_wallpaper_20_regular
	lightbulb = 0xEB3A, // ic_fluent_lightbulb_20_regular
	overview = 0xE991, // ic_fluent_glance_20_regular
	buy = 0xE3E2, // ic_fluent_cart_20_regular
	compare = 0xEAA1, // ic_fluent_item_compare_20_regular
	undo = 0xE1A5, // ic_fluent_arrow_undo_20_regular
	screen = 0xE685, // ic_fluent_desktop_20_regular
	question = 0xEF07, // ic_fluent_question_circle_20_regular
	block = 0xEEE3, // ic_fluent_prohibited_20_regular
	dock_bottom = 0xED22, // ic_fluent_panel_bottom_20_regular
	cloud = 0xE522, // ic_fluent_cloud_20_regular
	down = 0xE488, // ic_fluent_chevron_down_20_regular
	up = 0xE490, // ic_fluent_chevron_up_20_regular
	small_down = 0xE3D7, // ic_fluent_caret_down_20_filled
	small_up = 0xE3DF, // ic_fluent_caret_up_20_filled
	small_left = 0xE3DB, // ic_fluent_caret_left_20_filled
	small_right = 0xE3DD, // ic_fluent_caret_right_20_filled
	error = 0xE877, // ic_fluent_error_circle_20_regular
	bullet = 0xE4B3, // ic_fluent_circle_small_20_filled
	minimize = 0xEB4E, // ic_fluent_line_horizontal_1_20_regular
	maximize = 0xEC2A, // ic_fluent_maximize_20_regular
	restore = 0xF149, // ic_fluent_square_multiple_20_regular
	close = 0xE6D3, // ic_fluent_dismiss_20_regular
	move_to_folder = 0xE919, // ic_fluent_folder_swap_20_regular
	copy_to_folder = 0xE5DB, // ic_fluent_copy_arrow_right_20_regular
	person = 0xEDB3, // ic_fluent_person_20_regular
	download = 0xE0DD, // ic_fluent_arrow_download_20_regular
	pin = 0xEE75, // ic_fluent_pin_20_regular
	pinned = 0xEE74, // ic_fluent_pin_20_filled
	keyboard = 0xEAB1, // ic_fluent_keyboard_20_regular
	orientation = 0xED02, // ic_fluent_orientation_20_regular
	list = 0xEB7A, // ic_fluent_list_20_regular
	attach = 0xE1BB, // ic_fluent_attach_20_regular
	archive = 0xE91D, // ic_fluent_folder_zip_20_regular
	app = 0xE06D, // ic_fluent_app_generic_20_regular
	spreadsheet = 0xF1F1, // ic_fluent_table_20_regular
	image_vector = 0xE7E3, // ic_fluent_draw_shape_20_regular
	presentation = 0xF0B1, // ic_fluent_slide_layout_20_regular
	model3d = 0xE5F5, // ic_fluent_cube_20_regular
	code = 0xE54E, // ic_fluent_code_20_regular
	data = 0xE64D, // ic_fluent_database_20_regular
	retro = 0xE967, // ic_fluent_games_20_regular
	language = 0xEB88, // ic_fluent_local_language_20_regular
	edit_metadata = 0xE723, // ic_fluent_document_edit_20_regular
	verbose_metadata = 0xF35D, // ic_fluent_text_description_20_regular
	edit_cut = 0xE617, // ic_fluent_cut_20_regular
	edit_copy = 0xE5D7, // ic_fluent_copy_20_regular
	edit_paste = 0xE4F2, // ic_fluent_clipboard_paste_20_regular
	documentation = 0xE25A, // ic_fluent_book_open_20_regular
	support = 0xEE1D, // ic_fluent_person_support_20_regular
	verify = 0xE462, // ic_fluent_checkmark_circle_20_regular
	sync = 0xE171, // ic_fluent_arrow_sync_20_regular
	checkbox_off = 0xE45C, // ic_fluent_checkbox_unchecked_20_regular
	checkbox_on = 0xE453, // ic_fluent_checkbox_checked_20_filled
	radio_off = 0xE494, // ic_fluent_circle_20_regular
	radio_on = 0xEF12, // ic_fluent_radio_button_20_filled
	media_options = 0xECFA, // ic_fluent_options_20_regular
	unknown = 0xEF05, // ic_fluent_question_20_regular
	today = 0xE388, // ic_fluent_calendar_today_20_regular
	yesterday = 0xEA2E, // ic_fluent_history_20_regular
	set = 0xEADD, // ic_fluent_layer_diagonal_20_regular
	set_solid = 0xEADC, // ic_fluent_layer_diagonal_20_filled
	copyright = 0xA9,
};
