// This file is part of the Diffractor photo and video organizer
// Copyright 2026  Zac Walker
// 
// This program is free software; you can redistribute it and / or modify it
// under the terms of the LGPL License either version 2.1 or later.
// License details are available at https://www.gnu.org/licenses/lgpl-2.1.html
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY

// Purpose: Generates the "Formats and Codecs" wiki page from the live file type
// and codec tables the application itself dispatches on. Invoked from the command
// line via /gen-docs[:folder]. The metadata mapping is maintained by hand in
// docs/metadata.md because no single table in code describes it.

#include "pch.h"
#include "files.h"
#include "platform.h"
#include "av_format.h"

#include <cstdio>

namespace
{
	// Splits a comma separated extension list (e.g. "aif, aifc, aiff") into an
	// uppercased, normalised, comma separated string (e.g. "AIF, AIFC, AIFF").
	std::string format_extensions(const std::string_view extensions)
	{
		std::string result;

		for (const auto part : str::split(extensions, false, [](const wchar_t c) { return c == ','; }))
		{
			const auto trimmed = str::trim(part);
			if (trimmed.empty()) continue;

			if (!result.empty()) result += ", ";
			result += str::to_upper(trimmed);
		}

		return result;
	}

	// Markers that delimit the generated region within a wiki page. Text outside
	// these markers is hand-written narrative and is preserved across regenerations.
	constexpr std::string_view k_begin = "<!-- gen-docs:begin -->";
	constexpr std::string_view k_end = "<!-- gen-docs:end -->";

	// Note placed at the top of each generated block.
	constexpr std::string_view k_generated_note =
		"<!-- The tables in this section are generated by Diffractor "
		"(diffractor64.exe /gen-docs). Content between the gen-docs:begin and "
		"gen-docs:end markers is overwritten on each run; edit the surrounding "
		"text freely. -->\n\n";

	std::string read_text_file(const df::file_path path)
	{
		if (!platform::exists(path)) return {};
		const auto b = df::blob_from_file(path);
		return std::string(reinterpret_cast<const char*>(b.data()), b.size());
	}

	// Writes content to a wiki page, preserving any narrative outside the
	// gen-docs markers. If the existing page has both markers, only the region
	// between them is replaced with `block`. Otherwise the full `default_page`
	// (narrative shell + markers + block) is written.
	bool splice_and_save(const df::folder_path folder, const std::string_view file_name,
	                     const std::string& default_page, const std::string& block)
	{
		const auto path = folder.combine_file(file_name);
		const auto existing = read_text_file(path);

		std::string out;
		const auto b = existing.find(k_begin);
		const auto e = existing.find(k_end);

		if (b != std::string::npos && e != std::string::npos && e > b)
		{
			out.append(existing, 0, b + k_begin.size());
			out += "\n";
			out += block;
			out.append(existing, e, existing.size() - e);
			printf("  spliced %s (preserved surrounding text)\n", std::string(path.str()).c_str());
		}
		else
		{
			out = default_page;
			printf("  wrote %s (new page with markers)\n", std::string(path.str()).c_str());
		}

		const auto saved = df::blob_save_to_file(
			df::cspan(reinterpret_cast<const uint8_t*>(out.data()), out.size()), path);

		if (!saved)
		{
			printf("  ERROR: failed to write %s\n", std::string(path.str()).c_str());
		}

		return saved;
	}

	// Emits a markdown table of file types belonging to the given group, with an
	// optional raw-trait filter, including only types with a description.
	void write_format_table(std::string& md, const std::string_view section_title,
	                        const std::vector<file_type_ref>& types, const file_group_ref group,
	                        const bool require_raw, const bool exclude_raw)
	{
		md += "## ";
		md += section_title;
		md += "\n\n";
		md += "| Extensions | Description |\n";
		md += "| --- | --- |\n";

		for (const auto* ft : types)
		{
			if (ft->group != group) continue;
			if (ft->text.empty()) continue;

			const bool is_raw = ft->has_trait(file_traits::raw);
			if (require_raw && !is_raw) continue;
			if (exclude_raw && is_raw) continue;

			md += "| ";
			md += format_extensions(ft->extension);
			md += " | ";
			md += ft->text;
			md += " |\n";
		}

		md += "\n";
	}

	void write_codec_list(std::string& md, const std::string_view section_title,
	                      const std::vector<av_codec_doc>& codecs, const av_codec_media_type media_type)
	{
		md += "## ";
		md += section_title;
		md += "\n\n";

		bool first = true;

		for (const auto& c : codecs)
		{
			if (c.media_type != media_type) continue;
			if (c.name.empty()) continue;

			if (!first) md += ", ";
			md += c.name;
			first = false;
		}

		md += "\n\n";
	}

	bool generate_formats_page(const df::folder_path folder)
	{
		const auto types = all_file_types();
		const auto codecs = av_supported_codecs();

		std::string block;
		block += k_generated_note;
		write_format_table(block, "Image Formats", types, &file_group::photo, false, true);
		write_format_table(block, "Raw Photo Formats", types, &file_group::photo, true, false);
		write_format_table(block, "Video and Container Formats", types, &file_group::video, false, false);
		write_format_table(block, "Audio Formats", types, &file_group::audio, false, false);
		write_codec_list(block, "Video Codecs", codecs, av_codec_media_type::video);
		write_codec_list(block, "Audio Codecs", codecs, av_codec_media_type::audio);

		std::string default_page;
		default_page += "File formats and codecs supported by Diffractor are listed below.\n\n";
		default_page += k_begin;
		default_page += "\n";
		default_page += block;
		default_page += k_end;
		default_page += "\n";

		return splice_and_save(folder, "Formats-and-Codecs.md", default_page, block);
	}
}

int generate_wiki_docs(const std::string_view output_folder)
{
	load_file_types();

	const df::folder_path folder = output_folder.empty()
		                               ? platform::known_path(platform::known_folder::running_app_folder)
		                               : df::folder_path(output_folder);

	if (!platform::exists(folder))
	{
		platform::create_folder(folder);
	}

	if (!platform::exists(folder))
	{
		printf("ERROR: output folder does not exist: %s\n", std::string(folder.text().sv()).c_str());
		return 1;
	}

	printf("Generating wiki documentation in %s\n", std::string(folder.text().sv()).c_str());

	if (generate_formats_page(folder))
	{
		printf("Done.\n");
		return 0;
	}

	printf("Completed with errors.\n");
	return 1;
}
