name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: df.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026
    
    strategy:
      matrix:
        platform: ['Win32', 'x64']

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3
      with:
        vs-prerelease: true

    - name: Build x64
      if: matrix.platform == 'x64'
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win32
      if: matrix.platform == 'Win32'
      working-directory: ${{ github.workspace }}
      run: msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=Win32 ${{env.SOLUTION_FILE_PATH}}

    - name: Run x64 tests
      if: matrix.platform == 'x64'
      working-directory: ${{ github.workspace }}\exe
      run: .\diffractor64.exe /test

    - name: Run Win32 tests
      if: matrix.platform == 'Win32'
      working-directory: ${{ github.workspace }}\exe
      run: .\diffractor32.exe /test
